// https://git.libreoffice.org/core/+/refs/heads/master/filter/source/config/fragments/filters
[
  "HTML",
  "writerweb8_writer",
  "writerweb8_writer_template",
  "writer_web_StarOffice_XML_Writer",
  "Text (StarWriter/Web)",
  "Text (encoded) (StarWriter/Web)",
  "writer_web_jpg_Export",
  "writer_web_pdf_Export",
  "writer_web_png_Export",
  "writer8",
  "writer8_template",
  "OpenDocument Text Flat XML",
  "UOF text",
  "MS Word 2007 XML",
  "MS Word 2007 XML Template",
  "MS Word 2003 XML",
  "MS Word 97",
  "MS Word 97 Vorlage",
  "DocBook File",
  "HTML (StarWriter)",
  "Rich Text Format",
  "Text",
  "Text (encoded)",
  "Office Open XML Text",
  "EPUB",
  "MS Word 2007 XML VBA",
  "XHTML Writer File",
  "writer_indexing_export",
  "writer_jpg_Export",
  "writer_layout_dump",
  "writer_pdf_Export",
  "writer_png_Export",
  "writer_svg_Export",
  "writerglobal8",
  "Text (encoded) (StarWriter/GlobalDocument)",
  "writer_globaldocument_pdf_Export",
  "writerglobal8_HTML",
  "writerglobal8_template",
  "writerglobal8_writer",
  "chart8",
  "draw8",
  "draw8_template",
  "OpenDocument Drawing Flat XML",
  "draw_html_Export",
  "draw_pdf_Export",
  "XHTML Draw File",
  "draw_bmp_Export",
  "draw_emf_Export",
  "draw_eps_Export",
  "draw_gif_Export",
  "draw_jpg_Export",
  "draw_png_Export",
  "draw_svg_Export",
  "draw_tif_Export",
  "draw_wmf_Export",
  "math8",
  "MathML XML (Math)",
  "MathType 3.x",
  "math_pdf_Export",
  "calc8",
  "calc8_template",
  "OpenDocument Spreadsheet Flat XML",
  "UOF spreadsheet",
  "Calc MS Excel 2007 XML",
  "Calc MS Excel 2007 XML Template",
  "MS Excel 2003 XML",
  "MS Excel 97",
  "MS Excel 97 Vorlage/Template",
  "DIF",
  "dBase",
  "HTML (StarCalc)",
  "SYLK",
  "Text - txt - csv (StarCalc)",
  "Calc Office Open XML",
  "Calc MS Excel 2007 VBA XML",
  "XHTML Calc File",
  "calc_jpg_Export",
  "calc_pdf_Export",
  "calc_png_Export",
  "calc_svg_Export",
  "impress8",
  "impress8_template",
  "impress8_draw",
  "OpenDocument Presentation Flat XML",
  "UOF presentation",
  "Impress MS PowerPoint 2007 XML",
  "Impress MS PowerPoint 2007 XML AutoPlay",
  "Impress MS PowerPoint 2007 XML Template",
  "MS PowerPoint 97",
  "MS PowerPoint 97 AutoPlay",
  "MS PowerPoint 97 Vorlage",
  "Impress Office Open XML",
  "Impress Office Open XML AutoPlay",
  "Impress Office Open XML Template",
  "Impress MS PowerPoint 2007 XML VBA",
  "XHTML Impress File",
  "impress_bmp_Export",
  "impress_emf_Export",
  "impress_eps_Export",
  "impress_gif_Export",
  "impress_html_Export",
  "impress_jpg_Export",
  "impress_pdf_Export",
  "impress_png_Export",
  "impress_svg_Export",
  "impress_tif_Export",
  "impress_wmf_Export",
];
